export default {
  "login": "Jermaine-rbg",
  "id": 79242924,
  "node_id": "MDQ6VXNlcjc5MjQyOTI0",
  "avatar_url": "https://avatars.githubusercontent.com/u/79242924?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Jermaine-rbg",
  "html_url": "https://github.com/Jermaine-rbg",
  "followers_url": "https://api.github.com/users/Jermaine-rbg/followers",
  "following_url": "https://api.github.com/users/Jermaine-rbg/following{/other_user}",
  "gists_url": "https://api.github.com/users/Jermaine-rbg/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Jermaine-rbg/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Jermaine-rbg/subscriptions",
  "organizations_url": "https://api.github.com/users/Jermaine-rbg/orgs",
  "repos_url": "https://api.github.com/users/Jermaine-rbg/repos",
  "events_url": "https://api.github.com/users/Jermaine-rbg/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Jermaine-rbg/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Jermaine-rbg",
  "company": null,
  "blog": "https://www.linkedin.com/in/jermaine-bailey-727830187",
  "location": "Atlanta, Ga.",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 14,
  "public_gists": 0,
  "followers": 0,
  "following": 1,
  "created_at": "2021-02-18T05:24:25Z",
  "updated_at": "2021-09-25T04:12:13Z"
}